### PR TITLE
Using strings for keys

### PR DESCRIPTION
**Pull request by N8-Wright**
Using strings as the key values in MessagePack to make interop with javascript easier. The format (in JSON) looks like this

`BeginSessionRequest` looks like `[0,{"ProtocolVersion":1}]`
`Response` looks like `[1,{"ProtocolVersion":1,"ResponseCode":1}]`

### CODE REVIEW

**Comment by N8-Wright** [comment]
@nicfv Does this look like a usable format for you to implement on the client side?

**Comment by nicfv** [comment]
I don't have my computer this weekend so I'll check on Monday night! Thanks
for trying out that library on the server side!

**Comment by nicfv** [comment]
How do I approve the PR?

**Comment by N8-Wright** [comment]
Whoopsies made the repo rules too strict. Merging it now

**Pull request merged**
